defaultEntryPoints = ["http", "https"]
logLevel = "DEBUG"

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://34.76.78.240:80"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
  passHostHeader = true

[acme]
email = "knapiontek@gmail.com"
storage = "acme.json"
onHostRule = true
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"
  [[acme.domains]]
  main = "gecko.knapiontek.com"

[api]
  entryPoint = "traefik"
  dashboard = true
  debug = true
