debug = true
logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.dashboard]
  address = ":8080"

[api]
entrypoint = "dashboard"
dashboard = true
debug = true

[file]
  [frontends]
    [frontends.frontend_trade]
    backend = "backend_trade"
      [frontends.frontend_trade.routes.route_trade]
      rule = "Host:gecko-code.com"
  [backends]
    [backends.backend_trade]
      [backends.backend_trade.servers.server_trade]
      url = "http://34.76.78.240:80"
